"""Backward-compatible re-exports for structured payload schemas."""

from .base import (
    BaseTaskPayload,
    Entity,
    Relationship,
    ExtractedField,
    RiskItem,
    ActionItem,
    ExtractionPayload,
    Topic,
    SummaryPayload,
    ChecklistItem,
    ChecklistPayload,
    ContactInfo,
    EducationEntry,
    ExperienceEntry,
    CVSectionContentItem,
    CVSection,
    CVAnalysisPayload,
    CodeIssue,
    CodeAnalysisPayload,
    TaskPayload,
)

__all__ = [
    "BaseTaskPayload",
    "Entity",
    "Relationship",
    "ExtractedField",
    "RiskItem",
    "ActionItem",
    "ExtractionPayload",
    "Topic",
    "SummaryPayload",
    "ChecklistItem",
    "ChecklistPayload",
    "ContactInfo",
    "EducationEntry",
    "ExperienceEntry",
    "CVSectionContentItem",
    "CVSection",
    "CVAnalysisPayload",
    "CodeIssue",
    "CodeAnalysisPayload",
    "TaskPayload",
]
