FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends curl \
    && rm -rf /var/lib/apt/lists/*

COPY requirements-product-api.local.txt /app/requirements-product-api.local.txt
RUN pip install --upgrade pip \
    && pip install -r /app/requirements-product-api.local.txt

COPY . /app

EXPOSE 8011

CMD ["python", "main_product_api.py"]
