import type {
  ProviderConnection,
  RuntimeProfile,
  WorkflowDefault,
  ConnectionPolicyRule,
  OperatorPreferences,
} from '@/types/settings';

export const PROVIDER_CONNECTIONS: ProviderConnection[] = [
  {
    id: 'ollama-local',
    name: 'Ollama Local',
    providerFamily: 'ollama',
    mode: 'local',
    baseUrl: 'http://localhost:11434',
    authMethod: 'none',
    apiKeyConfigured: false,
    status: 'connected',
    preferredModel: 'qwen2.5:32b-instruct-q5_K_M',
    lastChecked: '2 min ago',
    description: 'Local Ollama daemon on GPU workstation. No API key required and suited to primary day-to-day execution.',
    capabilities: { generation: true, embeddings: true, reranking: false, structuredOutputs: true, vision: false, toolCalling: false, streaming: true },
    role: 'production',
    workflowFit: ['document-review', 'comparison', 'action-plan', 'candidate-review', 'chat-experiments', 'workflow-inspector'],
    usageNote: 'Primary production connection. Supports all core workflows with local GPU inference.',
  },
  {
    id: 'ollama-hosted',
    name: 'Ollama Hosted',
    providerFamily: 'ollama',
    mode: 'hosted',
    baseUrl: 'https://ollama.internal.example.com',
    authMethod: 'api_key',
    apiKeyConfigured: true,
    status: 'connected',
    preferredModel: 'llama3.1:70b-instruct-q4_K_M',
    lastChecked: '5 min ago',
    description: 'Remote Ollama endpoint on a shared GPU cluster for burst overflow, deep analysis, and long-context review.',
    capabilities: { generation: true, embeddings: true, reranking: false, structuredOutputs: true, vision: false, toolCalling: false, streaming: true },
    role: 'burst_overflow',
    workflowFit: ['document-review', 'comparison', 'action-plan'],
    usageNote: 'Burst overflow when local is unavailable. Also used as primary for deep review profiles.',
  },
  {
    id: 'huggingface',
    name: 'Hugging Face Inference',
    providerFamily: 'huggingface',
    mode: 'cloud',
    baseUrl: 'https://api-inference.huggingface.co',
    authMethod: 'bearer_token',
    apiKeyConfigured: true,
    status: 'connected',
    preferredModel: 'mistralai/Mixtral-8x7B-Instruct-v0.1',
    lastChecked: '8 min ago',
    description: 'Optional cloud endpoint for benchmarks, evals, and long-context review when workspace policy allows escalation.',
    capabilities: { generation: true, embeddings: true, reranking: false, structuredOutputs: false, vision: false, toolCalling: false, streaming: true },
    role: 'long_context',
    workflowFit: ['document-review', 'comparison', 'chat-experiments', 'workflow-inspector'],
    usageNote: 'Cloud endpoint kept available for optional hosted usage and benchmark comparisons.',
  },
  {
    id: 'openai-compat',
    name: 'OpenAI-Compatible Endpoint',
    providerFamily: 'openai_compatible',
    mode: 'openai-compatible',
    baseUrl: 'https://api.external-llm.example.com/v1',
    authMethod: 'api_key',
    apiKeyConfigured: false,
    status: 'not_configured',
    preferredModel: 'gpt-4o-mini',
    lastChecked: 'Never',
    description: 'Generic OpenAI-compatible reference endpoint for future benchmark comparisons and external integrations.',
    capabilities: { generation: true, embeddings: true, reranking: false, structuredOutputs: true, vision: true, toolCalling: true, streaming: true },
    role: 'benchmark_reference',
    workflowFit: ['chat-experiments', 'workflow-inspector'],
    usageNote: 'External reference for side-by-side comparison. Requires API key configuration.',
  },
];

export const ALL_WORKFLOWS = [
  { id: 'document-review', label: 'Document Review' },
  { id: 'comparison', label: 'Comparison' },
  { id: 'action-plan', label: 'Action Plan' },
  { id: 'candidate-review', label: 'Candidate Review' },
  { id: 'chat-experiments', label: 'Chat Experiments' },
  { id: 'workflow-inspector', label: 'Workflow Inspector' },
] as const;

export const RUNTIME_PROFILES: RuntimeProfile[] = [
  {
    id: 'local-production',
    name: 'Local First Production',
    primaryConnectionId: 'ollama-local',
    primaryModel: 'qwen2.5:32b-instruct-q5_K_M',
    fallbackChain: [
      { connectionId: 'ollama-hosted', model: 'llama3.1:70b-instruct-q4_K_M', label: 'Burst to hosted cluster' },
    ],
    executionPolicy: 'prefer_local_burst_hosted',
    retrievalStrategy: 'hybrid',
    embeddingConnectionId: 'ollama-local',
    embeddingModel: 'nomic-embed-text',
    rerankingEnabled: true,
    docProcessingPreset: 'standard',
    qualityPosture: 'max_quality',
    intendedWorkflows: ['document-review', 'comparison', 'action-plan'],
    isActive: true,
    isDefault: true,
    summary: 'Primary production profile using local GPU, hybrid retrieval, and reranking, with hosted Ollama as the first fallback.',
    generation: { temperature: 0.3, contextWindow: 'auto', promptProfile: 'balanced', streaming: true, maxOutputTokens: 4096, topP: 0.95, structuredOutput: false },
    retrieval: { topK: 15, chunkSize: 1200, chunkOverlap: 200, rerankPoolSize: 50, rerankLexicalWeight: 0.3, groundingStrictness: 'balanced' },
    docProcessing: { pdfExtractionMode: 'plumber', ocrBackend: 'tesseract', vlmEnhancement: false, tableExtractionMode: 'auto', ocrFailoverEnabled: true, scannedDocumentThreshold: 0.6 },
    workflowFit: [
      { workflowId: 'document-review', label: 'Document Review', compatibility: 'recommended', reason: 'Hybrid retrieval with reranking keeps output grounded in evidence.' },
      { workflowId: 'comparison', label: 'Comparison', compatibility: 'recommended', reason: 'Balanced generation with evidence linkage is a strong default.' },
      { workflowId: 'action-plan', label: 'Action Plan', compatibility: 'recommended', reason: 'Full context support helps multi-section planning.' },
      { workflowId: 'candidate-review', label: 'Candidate Review', compatibility: 'compatible', reason: 'Works well, though Fast Triage is more efficient for screening.' },
      { workflowId: 'chat-experiments', label: 'Chat Experiments', compatibility: 'compatible' },
      { workflowId: 'workflow-inspector', label: 'Workflow Inspector', compatibility: 'compatible', reason: 'Structured outputs are supported through Ollama Local.' },
    ],
  },
  {
    id: 'fast-triage',
    name: 'Fast Triage',
    primaryConnectionId: 'ollama-local',
    primaryModel: 'mistral:7b-instruct-v0.3',
    fallbackChain: [],
    executionPolicy: 'local_only',
    retrievalStrategy: 'lexical',
    embeddingConnectionId: 'ollama-local',
    embeddingModel: 'nomic-embed-text',
    rerankingEnabled: false,
    docProcessingPreset: 'fast_text',
    qualityPosture: 'low_latency',
    intendedWorkflows: ['candidate-review'],
    isActive: false,
    isDefault: false,
    summary: 'Quick screening profile with lightweight local inference, lexical retrieval, and fast text extraction.',
    generation: { temperature: 0.2, contextWindow: '4k', promptProfile: 'precise', streaming: true, maxOutputTokens: 1024, topP: 0.9, structuredOutput: false },
    retrieval: { topK: 8, chunkSize: 800, chunkOverlap: 100, rerankPoolSize: 0, rerankLexicalWeight: 1, groundingStrictness: 'permissive' },
    docProcessing: { pdfExtractionMode: 'plumber', ocrBackend: 'tesseract', vlmEnhancement: false, tableExtractionMode: 'auto', ocrFailoverEnabled: false, scannedDocumentThreshold: 0.8 },
    workflowFit: [
      { workflowId: 'candidate-review', label: 'Candidate Review', compatibility: 'recommended', reason: 'Optimized for fast screening with low latency.' },
      { workflowId: 'document-review', label: 'Document Review', compatibility: 'restricted', reason: 'Lexical-only retrieval may miss semantic evidence.' },
      { workflowId: 'comparison', label: 'Comparison', compatibility: 'restricted', reason: 'Small model may lack depth for nuanced comparison.' },
      { workflowId: 'action-plan', label: 'Action Plan', compatibility: 'restricted', reason: '4K context window limits multi-section analysis.' },
      { workflowId: 'chat-experiments', label: 'Chat Experiments', compatibility: 'compatible' },
      { workflowId: 'workflow-inspector', label: 'Workflow Inspector', compatibility: 'unsupported', reason: 'Structured outputs are unreliable for this small model.' },
    ],
  },
  {
    id: 'hosted-deep-review',
    name: 'Hosted Deep Review',
    primaryConnectionId: 'ollama-hosted',
    primaryModel: 'llama3.1:70b-instruct-q4_K_M',
    fallbackChain: [
      { connectionId: 'ollama-local', model: 'qwen2.5:32b-instruct-q5_K_M', label: 'Fall back to local GPU' },
    ],
    executionPolicy: 'hosted_deep_review',
    retrievalStrategy: 'hybrid',
    embeddingConnectionId: 'ollama-hosted',
    embeddingModel: 'bge-m3',
    rerankingEnabled: true,
    docProcessingPreset: 'vlm_enhanced',
    qualityPosture: 'max_quality',
    intendedWorkflows: ['document-review', 'comparison', 'action-plan'],
    isActive: false,
    isDefault: false,
    summary: 'Deep analysis on a remote 70B model with VLM-enhanced document processing for complex layouts.',
    generation: { temperature: 0.25, contextWindow: '32k', promptProfile: 'precise', streaming: true, maxOutputTokens: 8192, topP: 0.92, structuredOutput: false },
    retrieval: { topK: 25, chunkSize: 1600, chunkOverlap: 300, rerankPoolSize: 80, rerankLexicalWeight: 0.25, groundingStrictness: 'strict' },
    docProcessing: { pdfExtractionMode: 'marker', ocrBackend: 'surya', vlmEnhancement: true, tableExtractionMode: 'vlm', ocrFailoverEnabled: true, scannedDocumentThreshold: 0.4 },
    workflowFit: [
      { workflowId: 'document-review', label: 'Document Review', compatibility: 'recommended', reason: 'Strict grounding with 70B reasoning for high-stakes review.' },
      { workflowId: 'comparison', label: 'Comparison', compatibility: 'recommended', reason: 'Deep reasoning plus VLM help on complex layouts.' },
      { workflowId: 'action-plan', label: 'Action Plan', compatibility: 'recommended', reason: '32K context supports richer planning.' },
      { workflowId: 'candidate-review', label: 'Candidate Review', compatibility: 'compatible', reason: 'Works, but is more capacity than screening needs.' },
      { workflowId: 'chat-experiments', label: 'Chat Experiments', compatibility: 'compatible' },
      { workflowId: 'workflow-inspector', label: 'Workflow Inspector', compatibility: 'compatible', reason: 'Hosted Ollama still supports structured outputs.' },
    ],
  },
  {
    id: 'hf-long-context',
    name: 'HF Long Context Review',
    primaryConnectionId: 'huggingface',
    primaryModel: 'mistralai/Mixtral-8x7B-Instruct-v0.1',
    fallbackChain: [
      { connectionId: 'ollama-hosted', model: 'llama3.1:70b-instruct-q4_K_M', label: 'Fallback to hosted Ollama' },
    ],
    executionPolicy: 'cloud_selected_workflows',
    retrievalStrategy: 'semantic',
    embeddingConnectionId: 'ollama-local',
    embeddingModel: 'bge-m3',
    rerankingEnabled: true,
    docProcessingPreset: 'standard',
    qualityPosture: 'balanced',
    intendedWorkflows: ['document-review', 'comparison'],
    isActive: false,
    isDefault: false,
    summary: 'Optional cloud-based long-context review using Hugging Face when policy allows selected workflows to escalate.',
    generation: { temperature: 0.35, contextWindow: '32k', promptProfile: 'balanced', streaming: true, maxOutputTokens: 6144, topP: 0.95, structuredOutput: false },
    retrieval: { topK: 20, chunkSize: 1400, chunkOverlap: 250, rerankPoolSize: 60, rerankLexicalWeight: 0.2, groundingStrictness: 'balanced' },
    docProcessing: { pdfExtractionMode: 'plumber', ocrBackend: 'tesseract', vlmEnhancement: false, tableExtractionMode: 'auto', ocrFailoverEnabled: true, scannedDocumentThreshold: 0.6 },
    workflowFit: [
      { workflowId: 'document-review', label: 'Document Review', compatibility: 'recommended', reason: '32K context is ideal for full-document analysis.' },
      { workflowId: 'comparison', label: 'Comparison', compatibility: 'recommended', reason: 'Large context helps side-by-side reasoning.' },
      { workflowId: 'action-plan', label: 'Action Plan', compatibility: 'compatible', reason: 'Works, though cloud latency may affect interactive use.' },
      { workflowId: 'candidate-review', label: 'Candidate Review', compatibility: 'restricted', reason: 'Cloud overhead is too high for screening.' },
      { workflowId: 'chat-experiments', label: 'Chat Experiments', compatibility: 'compatible' },
      { workflowId: 'workflow-inspector', label: 'Workflow Inspector', compatibility: 'unsupported', reason: 'Structured outputs are not supported by this HF endpoint.' },
    ],
  },
  {
    id: 'hf-benchmark',
    name: 'External Benchmark Reference',
    primaryConnectionId: 'huggingface',
    primaryModel: 'mistralai/Mixtral-8x7B-Instruct-v0.1',
    fallbackChain: [],
    executionPolicy: 'benchmark_reference_only',
    retrievalStrategy: 'hybrid',
    embeddingConnectionId: 'ollama-local',
    embeddingModel: 'bge-m3',
    rerankingEnabled: true,
    docProcessingPreset: 'standard',
    qualityPosture: 'balanced',
    intendedWorkflows: ['chat-experiments', 'workflow-inspector'],
    isActive: false,
    isDefault: false,
    summary: 'External reference profile for benchmarks and eval baselines. Cloud usage is restricted to comparison-style workloads.',
    generation: { temperature: 0.3, contextWindow: 'auto', promptProfile: 'balanced', streaming: true, maxOutputTokens: 4096, topP: 0.95, structuredOutput: false },
    retrieval: { topK: 15, chunkSize: 1200, chunkOverlap: 200, rerankPoolSize: 50, rerankLexicalWeight: 0.3, groundingStrictness: 'balanced' },
    docProcessing: { pdfExtractionMode: 'plumber', ocrBackend: 'tesseract', vlmEnhancement: false, tableExtractionMode: 'auto', ocrFailoverEnabled: true, scannedDocumentThreshold: 0.6 },
    workflowFit: [
      { workflowId: 'chat-experiments', label: 'Chat Experiments', compatibility: 'recommended', reason: 'Useful for A/B comparison against local models.' },
      { workflowId: 'workflow-inspector', label: 'Workflow Inspector', compatibility: 'restricted', reason: 'Structured outputs are not supported, so this is comparison-only.' },
      { workflowId: 'document-review', label: 'Document Review', compatibility: 'restricted', reason: 'Policy restricts cloud use for production workflows.' },
      { workflowId: 'comparison', label: 'Comparison', compatibility: 'restricted', reason: 'Policy restricts cloud use for production workflows.' },
      { workflowId: 'action-plan', label: 'Action Plan', compatibility: 'restricted', reason: 'Policy restricts cloud use for production workflows.' },
      { workflowId: 'candidate-review', label: 'Candidate Review', compatibility: 'unsupported', reason: 'Not suited to candidate screening.' },
    ],
  },
  {
    id: 'openai-compat-ref',
    name: 'OpenAI-Compatible Reference',
    primaryConnectionId: 'openai-compat',
    primaryModel: 'gpt-4o-mini',
    fallbackChain: [],
    executionPolicy: 'benchmark_reference_only',
    retrievalStrategy: 'hybrid',
    embeddingConnectionId: 'ollama-local',
    embeddingModel: 'nomic-embed-text',
    rerankingEnabled: false,
    docProcessingPreset: 'standard',
    qualityPosture: 'balanced',
    intendedWorkflows: ['chat-experiments', 'workflow-inspector'],
    isActive: false,
    isDefault: false,
    summary: 'OpenAI-compatible external reference kept as a future comparison endpoint and benchmark baseline.',
    generation: { temperature: 0.3, contextWindow: 'auto', promptProfile: 'balanced', streaming: true, maxOutputTokens: 4096, topP: 0.95, structuredOutput: true },
    retrieval: { topK: 15, chunkSize: 1200, chunkOverlap: 200, rerankPoolSize: 0, rerankLexicalWeight: 0.3, groundingStrictness: 'balanced' },
    docProcessing: { pdfExtractionMode: 'plumber', ocrBackend: 'tesseract', vlmEnhancement: false, tableExtractionMode: 'auto', ocrFailoverEnabled: true, scannedDocumentThreshold: 0.6 },
    workflowFit: [
      { workflowId: 'chat-experiments', label: 'Chat Experiments', compatibility: 'recommended', reason: 'Strong comparison target with broader capability coverage.' },
      { workflowId: 'workflow-inspector', label: 'Workflow Inspector', compatibility: 'recommended', reason: 'Structured outputs and tool calling are supported.' },
      { workflowId: 'document-review', label: 'Document Review', compatibility: 'restricted', reason: 'Policy keeps this endpoint in benchmark mode only.' },
      { workflowId: 'comparison', label: 'Comparison', compatibility: 'restricted', reason: 'Policy keeps this endpoint in benchmark mode only.' },
      { workflowId: 'action-plan', label: 'Action Plan', compatibility: 'restricted', reason: 'Policy keeps this endpoint in benchmark mode only.' },
      { workflowId: 'candidate-review', label: 'Candidate Review', compatibility: 'unsupported', reason: 'Not intended for screening workloads.' },
    ],
  },
];

export const DEFAULT_WORKFLOW_DEFAULTS: WorkflowDefault[] = [
  { workflowId: 'document-review', label: 'Document Review', profileId: 'local-production' },
  { workflowId: 'comparison', label: 'Comparison', profileId: 'local-production' },
  { workflowId: 'action-plan', label: 'Action Plan', profileId: 'local-production' },
  { workflowId: 'candidate-review', label: 'Candidate Review', profileId: 'fast-triage' },
  { workflowId: 'chat-experiments', label: 'Chat Experiments', profileId: 'local-production' },
  { workflowId: 'workflow-inspector', label: 'Workflow Inspector', profileId: 'local-production' },
];

export const CONNECTION_POLICY_RULES: ConnectionPolicyRule[] = [
  { id: 'allow-hosted-overflow', label: 'Allow hosted burst overflow', description: 'When local GPU is unavailable, production profiles may burst to hosted Ollama.', enabled: true },
  { id: 'hosted-deep-review', label: 'Allow hosted for deep review', description: 'Hosted connections may be used as primary for high-depth review profiles.', enabled: true },
  { id: 'cloud-selected-workflows', label: 'Allow cloud for selected workflows', description: 'Cloud providers such as Hugging Face may be used when explicitly assigned by profile.', enabled: false },
  { id: 'cloud-benchmarks-only', label: 'Restrict cloud to benchmarks/evals', description: 'When enabled, cloud reference models are limited to benchmark and eval workflows.', enabled: true },
  { id: 'require-structured-inspector', label: 'Require structured output for Inspector', description: 'Workflow Inspector should resolve to a connection supporting structured outputs.', enabled: true },
  { id: 'require-evidence-strict', label: 'Require evidence-safe review defaults', description: 'Document Review and Comparison should stay within balanced or strict grounding.', enabled: true },
];

export const DEFAULT_OPERATOR_PREFERENCES: OperatorPreferences = {
  reducedMotion: false,
  defaultEvidencePanelOpen: true,
  defaultExportFormat: 'pdf',
  defaultBenchmarkBaseline: 'local-production',
  showSourceBadges: true,
  autoOpenInspectorDetails: false,
};

export function getConnection(id: string): ProviderConnection | undefined {
  return PROVIDER_CONNECTIONS.find((connection) => connection.id === id);
}

export function getProfile(id: string): RuntimeProfile | undefined {
  return RUNTIME_PROFILES.find((profile) => profile.id === id);
}

export function getActiveProfile(): RuntimeProfile {
  return RUNTIME_PROFILES.find((profile) => profile.isActive) ?? RUNTIME_PROFILES[0];
}

export const EXECUTION_POLICY_LABELS: Record<string, { label: string; description: string }> = {
  local_only: { label: 'Local Only', description: 'Strictly local execution. Fail hard if unavailable.' },
  prefer_local_burst_hosted: { label: 'Prefer Local · Burst to Hosted', description: 'Uses local GPU first and bursts to hosted only when needed.' },
  hosted_only: { label: 'Hosted Only', description: 'Always uses a remote hosted endpoint.' },
  hosted_deep_review: { label: 'Hosted · Deep Review', description: 'Hosted cluster is primary for deep analysis, with local fallback.' },
  cloud_reference_only: { label: 'Cloud Reference Only', description: 'Cloud provider intended for benchmark and eval reference.' },
  cloud_selected_workflows: { label: 'Cloud · Selected Workflows', description: 'Cloud provider allowed only for explicitly assigned workflows.' },
  benchmark_reference_only: { label: 'Benchmark Reference Only', description: 'External reference used only for side-by-side comparison.' },
};

export const QUALITY_POSTURE_LABELS: Record<string, string> = {
  max_quality: 'Max Quality',
  balanced: 'Balanced',
  low_latency: 'Low Latency',
  cost_optimized: 'Cost Optimized',
};

export const DOC_PRESET_LABELS: Record<string, string> = {
  standard: 'Standard',
  ocr_heavy: 'OCR Heavy',
  vlm_enhanced: 'VLM Enhanced',
  fast_text: 'Fast Text',
};

export const CONNECTION_ROLE_LABELS: Record<string, string> = {
  production: 'Production',
  benchmark_reference: 'Benchmark',
  burst_overflow: 'Burst / Overflow',
  local_dev: 'Local Dev',
  deep_review: 'Deep Review',
  long_context: 'Long Context',
};

export const COMPATIBILITY_COLORS: Record<string, { bg: string; text: string; border: string }> = {
  recommended: { bg: 'bg-glow-success/10', text: 'text-glow-success', border: 'border-glow-success/20' },
  compatible: { bg: 'bg-primary/10', text: 'text-primary', border: 'border-primary/20' },
  restricted: { bg: 'bg-glow-warning/10', text: 'text-glow-warning', border: 'border-glow-warning/20' },
  unsupported: { bg: 'bg-glow-error/10', text: 'text-glow-error', border: 'border-glow-error/20' },
};